apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: dbauth
  name: dbauth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dbauth
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: dbauth
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          value: Y
        - name: SA_PASSWORD
          value: Koekje0495
        image: beauzaby/db-auth-jetter:dev
        imagePullPolicy: ""
        name: dbauth
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
