apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: dbjetter
  name: dbjetter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dbjetter
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: dbjetter
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          value: Y
        - name: SA_PASSWORD
          value: Koekje0495
        image: beauzaby/db-jeet-jetter:dev
        imagePullPolicy: ""
        name: dbjetter
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
