apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: gatewayservice
  name: gatewayservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gatewayservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: gatewayservice
    spec:
      containers:
      - image: beauzaby/gatewayservice-jetter:latest
        imagePullPolicy: ""
        name: gatewayservice
        ports:
        - containerPort: 5020
        - containerPort: 5021
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
