apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: jeetservice
  name: jeetservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jeetservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: jeetservice
    spec:
      containers:
      - image: beauzaby/jeetservice-jetter:latest
        imagePullPolicy: ""
        name: jeetservice
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
