apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: profileservice
  name: profileservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: profileservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: profileservice
    spec:
      containers:
      - image: beauzaby/profileservice-jetter:latest
        imagePullPolicy: ""
        name: profileservice
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
