apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: timelineservice
  name: timelineservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: timelineservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: timelineservice
    spec:
      containers:
      - image: beauzaby/timelineservice-jetter:latest
        imagePullPolicy: ""
        name: timelineservice
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
